name: dingo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  flutter_image: ^4.1.11
  flutter_image_compress: ^2.3.0
  tflite_flutter: ^0.11.0
  tflite:

  table_calendar: 
  permission_handler: 
  image_picker: 
  image: ^4.2.0   
  cached_network_image: ^3.4.1         
  camera:
  provider: 
  geolocator: ^13.0.1
  weather_icons: ^3.0.0

  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.3
  weather: 
  intl: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  
  fonts:
    - family: DreamCottage
      fonts:
        - asset: assets/fonts/dream_cottage/DreamCottage-Regular.otf
    - family: Frista
      fonts:
        - asset: assets/fonts/frista/FRISTARegular.otf
        - asset: assets/fonts/frista/FRISTARegular.ttf

  assets:
    - assets/images/ermo.webp
    - assets/images/blueErmo.webp
    - assets/images/greenErmo.webp
    - assets/model.tflite

